### ISSUE TITLE
Help Parameter

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [S3cur3Th1sSh1t/WinPwn#11]
Add help parameter for noninteractive + Consoleoutput

**Comment by artofwar2306** [comment]
Hey Mate! i had a look at all the changes you made and that is beautiful to see. One hell of an effort and i really appreciate your gift to the community. THANK YOU ! for such an awesome tool

**Comment by S3cur3Th1sSh1t** [comment]
527ed0c6e9ccebc80e14e7992033929deffcb8ce
