### ISSUE TITLE
Option 4 & 5 - from Offline_WinPwn.ps1 not working as expected

### ISSUE THREAD

**Issue by sp00ks-git** [S3cur3Th1sSh1t/WinPwn#12]
When using the Offline_WinPwn.ps1 and selecting option 4 from the menu - powershell version 5.1 and using rasta-mouses's AMSI bypass im seeing the following error message display to the terminal.

Option 4
Please choose wisely, master:: 4
Find-InterestingDomainShareFile : The term 'Find-InterestingDomainShareFile' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\temp\Offline_WinPwn.ps1:1963 char:16
+              4{Find-InterestingDomainShareFile >> "$currentPath\Domai ...
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Find-InterestingDomainShareFile:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Option 5 
Please choose wisely, master:: 5
Creating/Checking Log Folders in  C:\temp directory:
iex : At line:1 char:1
+
This script contains malicious content and has been blocked by your antivirus software.
At C:\temp\Offline_WinPwn.ps1:3396 char:337014
+ ... bDMyJ10NCiR2SlhjZW1kYlZoTnlOUUMgPSAkVHlwZXNbJ3d0c2FwaTMyJ10=")) | iex
+                                                                       ~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent,Microsoft.PowerShell.Commands.InvokeExpressionCommand

Searching for sensitive Files on the Domain-Network, this can take a while:
Claire : The term 'Claire' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At C:\temp\Offline_WinPwn.ps1:3398 char:25
+     if(!$consoleoutput){Claire >> $currentPath\SensitiveFiles.txt}els ...
+                         ~~~~~~
    + CategoryInfo          : ObjectNotFound: (Claire:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

shift : The term 'shift' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At C:\temp\Offline_WinPwn.ps1:3399 char:25
+     if(!$consoleoutput){shift -qgsNZggitoinaTA >> $currentPath\Networ ...
+                         ~~~~~
    + CategoryInfo          : ObjectNotFound: (shift:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by sp00ks-git** [comment]
Interesting that the 5 option has been detected by AV. Maybe this was the cause for option5.
"This script contains malicious content and has been blocked by your antivirus software"

**Comment by S3cur3Th1sSh1t** [comment]
Thanks for testing, i did not have the time so far. 👍 

Looks like i forgot to import Powerview for `Find-InterestingDomainShareFile` 
The other functions are from the string replaced PowerView version. I´ll fix that.

If you applied an AMSI bypass you should´t get any `This script contains malicious content and has been blocked by your antivirus software.` messages. 
Depending on the AV-Software installed its possible that it hooks every single command and checks it via AMSI. If thats the case your AMSI bypass is useless and you need a new process with BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_ON set.

**Comment by sp00ks-git** [comment]
Yes i also thought this was odd. Im looking again now and starting with a fresh powershell window, powershell -exec bypass , AMSI bypass then just going into menu 3  i see the same AV message which wasnt doing that before.

There is things like Crowd Strike and Alienvault in play which might be playing a part?

"================ WinPwn ================
Please choose wisely, master:: 7
================ WinPwn ================
1. Execute Inveigh - ADIDNS/LLMNR/mDNS/NBNS spoofer!
2. Local recon menu!
3. Domain recon menu!
4. Local privilege escalation check menu!
5. Get SYSTEM using Windows vulnerabilities!
6. Bypass UAC!
7. Get a SYSTEM Shell!
8. Kerberoasting!
9. Loot local Credentials!
10. Create an ADIDNS node or remove it!
11. Sessiongopher!
12. Kill the event log services for stealth!
13. PowerSharpPack menu!
14. Load custom C# Binaries from a webserver to Memory and execute them!
15. DomainPasswordSpray Attacks!
16. Reflectively load Mimik@tz into memory!
17. Exit.
================ WinPwn ================
Please choose wisely, master:: 3
Creating/Checking Log Folders in  C:\temp directory:
iex : At line:1 char:1
+
This script contains malicious content and has been blocked by your antivirus software.
At C:\temp\Offline_WinPwn.ps1:1887 char:98
+ ... 8.GetString([System.Convert]::FromBase64String("$viewdevobfs")) | iex
+                                                                       ~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent,Microsoft.PowerShell.Commands.InvokeExpressionCommand
"

**Comment by S3cur3Th1sSh1t** [comment]
`There is things like Crowd Strike and Alienvault in play` - most likely a hook. 

1) If you find out which DLL is hooking your process you can also bypass this with [SharpBlock](https://github.com/CCob/SharpBlock).

2) BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_ON, for example [ThisOne](https://gist.github.com/S3cur3Th1sSh1t/3b39648c786c5be359a987978b0a6137) with the command `Run-SecurePS`. In the new Powershell process the hook should be blocked.

**Comment by S3cur3Th1sSh1t** [comment]
The missing function name issue should be fixed here 672436941047b6e521aff7b02d51046d1324ce31

**Comment by sp00ks-git** [comment]
Thanks. I'll test again tomorrow and report back.

**Comment by sp00ks-git** [comment]
in option3 -> option 4 im now seeing "dnshostname" cannot be found.

![image](https://user-images.githubusercontent.com/56547010/96997757-47106a80-152a-11eb-8766-9389c31a2b8b.png)

**Comment by S3cur3Th1sSh1t** [comment]
Thats not a `WinPwn` issue but a Powerview issue. Is the System domain joined?

**Comment by sp00ks-git** [comment]
Yes it is definitely domain joined, i just noticed however it is using Powershell version 4.

**Comment by S3cur3Th1sSh1t** [comment]
If you find more feel free to open the issue again ;-)
