### ISSUE TITLE
mimikatz update request

### ISSUE THREAD

**Issue by sp00ks-git** [S3cur3Th1sSh1t/WinPwn#21]
Hi Can you update mimikatz to 2.2.0 20210701 PrintNightmare please?

**Comment by S3cur3Th1sSh1t** [comment]
Updated in in the Creds repo. The Offline version will get an Update later on.

https://github.com/S3cur3Th1sSh1t/Creds/commit/c91526c9ef47107b80109fafee97a6a4b3a543d0
