### ISSUE TITLE
ClearText password in shared folder issue

### ISSUE THREAD

**Issue by PentesterTN** [S3cur3Th1sSh1t/WinPwn#24]
everytime I choose to search for cleartext password in shared folder I got this error :

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

You cannot call a method on a null-valued expression.
At line:4384 char:13
+             $Increment = $SHARE_INFO_1::GetSize()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

You cannot call a method on a null-valued expression.
At line:4384 char:13
+             $Increment = $SHARE_INFO_1::GetSize()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

You cannot call a method on a null-valued expression.
At line:4384 char:13
+             $Increment = $SHARE_INFO_1::GetSize()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

You cannot call a method on a null-valued expression.
At line:4384 char:13
+             $Increment = $SHARE_INFO_1::GetSize()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

You cannot call a method on a null-valued expression.
At line:4384 char:13
+             $Increment = $SHARE_INFO_1::GetSize()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

You cannot call a method on a null-valued expression.
At line:4384 char:13
+             $Increment = $SHARE_INFO_1::GetSize()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

The right operand of '-as' must be a type.
At line:4391 char:17
+                 $Info = $NewIntPtr -as $SHARE_INFO_1
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : AsOperatorRequiresType

**Comment by S3cur3Th1sSh1t** [comment]
Via Passhunt or via Snaffler?

**Comment by PentesterTN** [comment]
it was via passhunt

**Comment by S3cur3Th1sSh1t** [comment]
Should be fixed with 700801a5fbe6e72a8165cec4e40d62a3400e2f5b. Can you re-check?

**Comment by PentesterTN** [comment]
after testing, it took like 9 hours Searching for Shares on the found Windows Servers..., then when I clicked any button it opened dozens of powershell windows, I had to force close them.

**Comment by PentesterTN** [comment]
I believe it's because I'm testing it against a large environment (+2000 servers)

**Comment by S3cur3Th1sSh1t** [comment]
I had a same situation from time to time. Running this check in a big environment will typically cause this issue - the CPU can’t handle too many share searches in parallel processes. 

But now you should have a list for all shares in the domainrecon folder. I would reduce the size of this list and choose only the interesting ones. Afterwards you can run the check again and it will take the existing list 👍 should be fine for the CPU than.

**Comment by PentesterTN** [comment]
I see, so now I think I can close this, Thank you for your support and gg for such a great tool!
