### ISSUE TITLE
Console Output only

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [S3cur3Th1sSh1t/WinPwn#3]
Add a switch to not write output to files but to the console.

**Comment by artofwar2306** [comment]
Hey man, great script, i was wondering if you had time to update the script to output to a console, like for example when using a C2 i would like to run WinPwn in a way that would display output onto my console directly is that possible?
Cheers

**Comment by S3cur3Th1sSh1t** [comment]
I opened the issue as a reminder for myself with the same use case. This change takes much more time because it affects the whole script, didn’t have enough time for it yet. But it’s on the agenda.

**Comment by artofwar2306** [comment]
awesome i understand mate :-) not easy balancing work and personal projects

**Comment by S3cur3Th1sSh1t** [comment]
Check this out, i´ll also update the Offline version in the next days and add an -help parameter.

0421dc401b16fbd7b15067cfd177085e74e1d686

**Comment by artofwar2306** [comment]
You are a legend!! cheers mate
