### ISSUE TITLE
Obfuscated AzureAD

### ISSUE THREAD

**Issue by sp00ks-git** [S3cur3Th1sSh1t/WinPwn#32]
Hi, Be really good to see an obfuscated version of AzureAD in here that would collect data for BloodHound Analysis.

https://raw.githubusercontent.com/BloodHoundAD/AzureHound/master/AzureHound.ps1

**Comment by S3cur3Th1sSh1t** [comment]
I won't install new Powershell modules on customers clients or servers. That's out of scope most times. So this would need the modules to be loaded without installation.

**Comment by S3cur3Th1sSh1t** [comment]
I decided to not add any cloud modules here. WinPwn is designed to be run from a compromised system. And all cloud checks can be run from a non domain joined attacker host.

 Therefore it’s just not needed here and would just increase the size.
