### ISSUE TITLE
Add Bloodhound multi-domain compatibility

### ISSUE THREAD

**Issue by 0x23353435** [S3cur3Th1sSh1t/WinPwn#33]
It would be nice if you add an option for the Bloodhound execution to use it for other domains in a forest with its -d parameter.

**Comment by S3cur3Th1sSh1t** [comment]
I’ll do that when I find the time 👍

**Comment by LuemmelSec** [comment]
See PR #34

**Comment by S3cur3Th1sSh1t** [comment]
Merged and integrated with:

https://github.com/S3cur3Th1sSh1t/WinPwn/commit/b5c29bc77777b3ed1c6a09cabdd4bc191a3e795c
