### ISSUE TITLE
I am unable to get NTLM Hashes using Inveigh using WinPwn but Invoke-Inveigh works just fine.

### ISSUE THREAD

**Issue by IAMinZoho** [S3cur3Th1sSh1t/WinPwn#39]
First of all thanks for your swift response!!

I am not sure if this is a issue ( I am just a script kiddie ;-)) Please check the screenshot using Kevin-Robertson's script:

![Capture](https://user-images.githubusercontent.com/84743508/178007984-08bdcccb-21c3-404b-b5de-8a715edaf570.PNG)

But using WinPwn I am unable to get it working:

![Capture11](https://user-images.githubusercontent.com/84743508/178008253-dff14150-ca98-4f13-b2a4-4897e9f240e1.JPG)

This time I must be doing something wrong. Please help.

**Comment by S3cur3Th1sSh1t** [comment]
Well. You should start reading the code to understand what it does. 😉 I’m specifying parameters for inveigh to dump the hashes into a file instead of console output. So that’s why you can’t see incoming hashes. 🤷‍♂️ But there is an output directory instead.

**Comment by IAMinZoho** [comment]
I did check the directory but no file is created. Nothing that shows the ntlm hashes.

**Comment by IAMinZoho** [comment]
I tried everything. Is there any logs that I can share.
