### ISSUE TITLE
WinPwn launching problem

### ISSUE THREAD

**Issue by piedacoulisse2** [S3cur3Th1sSh1t/WinPwn#40]
Hello, 

I run WinPwn on windows 10 pro dev : https://developer.microsoft.com/fr-fr/windows/downloads/virtual-machines/

I desactive Windows Defender and launch the ps1 but nothing append. 

![image](https://user-images.githubusercontent.com/74360897/178124192-b6f64277-9739-4f23-b143-715d9e013ca4.png)

**Comment by IAMinZoho** [comment]
This is not an issue. Please check the screenshot!
![Capture](https://user-images.githubusercontent.com/84743508/178153132-5a7f2c94-be60-4e0f-8ec7-9b0c3ad5bdc7.PNG)

**Comment by LuemmelSec** [comment]
The screenshot and the info you provide just say nothing. Please be more precise.

**Comment by S3cur3Th1sSh1t** [comment]
Exactly. He did not execute a function but a non existent script with .\WinPwn
