### ISSUE TITLE
While performing Situational Analysis for Domain I get this errors

### ISSUE THREAD

**Issue by IAMinZoho** [S3cur3Th1sSh1t/WinPwn#41]
Please check the screenshot.

![Capture](https://user-images.githubusercontent.com/84743508/178153430-eb74573b-74e2-4f48-82cd-3f1dd841c60e.PNG)

Any comments, please?

**Comment by S3cur3Th1sSh1t** [comment]
Must be something with your domain. In some environment single functions or scripts I embedded make problems. There will be errors for some checks anytime.

but I can’t replicate this so it’s something in your environment. 🤷‍♂️

**Comment by S3cur3Th1sSh1t** [comment]
If that happens I recommend you to take a look at the source code and try the functions manually.

**Comment by IAMinZoho** [comment]
Thank you for your response. I will check that. Forgive me for forgetting to mention this all the time! I love your work.
