### ISSUE TITLE
Just like Mimikatz Obfuscated with the freedom to run custom commands, can we have the same feature for Rubeus as well!

### ISSUE THREAD

**Issue by IAMinZoho** [S3cur3Th1sSh1t/WinPwn#46]
Is there a way we can load Rubeus and allow users to execute custom Rubeus functions like Mimikatz menu offers ( option 16 ) in WinPwn, e.g. 
.\Rubeus.exe asreproast  /format:<AS_REP_responses_format [hashcat | john]> /outfile:<output_hashes_file>

Thanks!

**Comment by IAMinZoho** [comment]
I did discover another masterpiece... PowerSharpPack!!! So the question how can i run PowerSharpPack -Rubeus from WinPwn?

**Comment by S3cur3Th1sSh1t** [comment]
I’m not planning to build a wrapper logic around Invoke-Rubeus at the moment. But this should actually be easy. I’ll let this open as a reminder for myself.

Also, I would not use the PowerSharpPack Script but the Invoke-Rubeus standalone ps1 file as that’s more up to date.

**Comment by IAMinZoho** [comment]
Thanks for considering this! I was trying to use `Rubeus.exe monitor /interval:30` from PowerSharpPack but the CLI was not refreshing (my guess..) and new TGTs were not shown. I will use Invoke-Rubeus but I love the idea of having Rubeus in my favorite WinPwn :-)

**Comment by S3cur3Th1sSh1t** [comment]
The problem in this case is, that you will only see the output after rubeus terminating. And it won’t terminate with that arguments, so you can never see the output. 

But removing the three lines before and after executing the main function for the console output this behaviour will change and you will see live output.

**Comment by S3cur3Th1sSh1t** [comment]
Here it is

https://github.com/S3cur3Th1sSh1t/WinPwn/commit/de0000ca7ebbaee5e34e11ef6bb7a6722f2da7f1
