### ISSUE TITLE
How can I pass parameters to mimiload command?

### ISSUE THREAD

**Issue by iamalsaher** [S3cur3Th1sSh1t/WinPwn#49]
I am looking to pass parameters to mimiload command so that it can be completely non interactive, but the mimiload directly loads the obfuscated mimikatz

How can I pass commands, I am looking for something like

`mimiload -consoleoutput -noninteractive -command "coffee exit"`

This doesn't seem to work

**Comment by S3cur3Th1sSh1t** [comment]
It's not possible to pass arguments to this function. You would need to take the script, and modify it. In the very end it's `Invoke-ReflectivePEInjection` with a customized Mimikatz Version, so you can pass parameters with the `-exeArgs` flag from `Invoke-ReflectivePEInjection`.

But it's also not meant to be used noninteractively here.
