### ISSUE TITLE
Logic error？

### ISSUE THREAD

**Issue by five-three** [S3cur3Th1sSh1t/WinPwn#51]
![image](https://github.com/S3cur3Th1sSh1t/WinPwn/assets/60723281/a2e4e08b-6139-4c25-ab94-ed6f6e4a7ed0)
This judgment always seems to be true

**Comment by S3cur3Th1sSh1t** [comment]
You are right. Good catch, fixed with f1f14f52d1ce292d756cef05b78273665454d612
