### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ankushgoel27** [S3cur3Th1sSh1t/WinPwn#6]
![image](https://user-images.githubusercontent.com/10580970/83968388-82492e80-a8e6-11ea-872e-0d4f0de007e2.png)

Not sure if this is unique to me but I am seeing this error being displayed non stop continously.

**Comment by S3cur3Th1sSh1t** [comment]
I cannot replicate this issue, some more context? What exactly did you run?

The lines of your error are from the browserpwn function which is working fine on my system.

**Comment by S3cur3Th1sSh1t** [comment]
Without any further context or descriptions i´ll close this now. Feel free to re-open if you got more informations.
