### ISSUE TITLE
Bloodhound update 

### ISSUE THREAD

**Issue by sp00ks-git** [S3cur3Th1sSh1t/WinPwn#8]
Hi can you update the sharphound collector to the latest version please.

**Comment by S3cur3Th1sSh1t** [comment]
It is version 3, did they release an significant update?

![grafik](https://user-images.githubusercontent.com/27858067/94270134-eba98780-ff3f-11ea-9910-0866a79dc24e.png)

**Comment by sp00ks-git** [comment]
The format of time stamps is dispalyed as TMPSTAMP in Sharphound and doesn't correctly show the last logon time, password changed etc. 
Also the cypher to pull this wont work either because of the older version.

I confirmed in the bloodhound slack this was the case. Just a bit annoying is all.

**Comment by sp00ks-git** [comment]
You could pull it directly from the official site, then it would be always up to date?

https://raw.githubusercontent.com/BloodHoundAD/BloodHound/master/Ingestors/SharpHound.ps1

**Comment by S3cur3Th1sSh1t** [comment]
Im not using the Powershell Script but my own compiled and string obfuscated version loaded via ```assembly::load()``` in another PowerSharpPack binary. Maybe there is some problem with the "obfuscation" so that the .json files broke. I´ll take a loot at it.

**Comment by S3cur3Th1sSh1t** [comment]
I did build a new version, which is only replacing some basic strings from SharpHound. Can you test the new version for the issue?

**Comment by sp00ks-git** [comment]
Yeah looks working now, thanks.
